# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eafe9dde38e61d56a856fe770bbbaf239ac7fd821e38ccc286d09bc2dd076724e975672c994099da4b04055d4971b9bd5fb7acd873f23f19451d96e4455022f

test:
  secret_key_base: 98ab2cdf4bbe1b847dcfe36a2b8915cd72c5f8ef92ef723527e88c40ed9b5c5ddf3bda543867d3a8e3c5da312e95e81de9f1ed8c58ea3af6bc5088607ca035fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
